/**
 * Emit Cloudflare Assets `_headers` from build-time env (with typed defaults).
 * Run via `pnpm headers` / prebuild — do not commit the generated file.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const DEFAULT_ASTRO_ASSET_CACHE_CONTROL = "public, max-age=31536000, immutable";
const DEFAULT_HTML_CACHE_CONTROL = "public, max-age=86400, must-revalidate";

const astroAssets =
  process.env.ASTRO_ASSET_CACHE_CONTROL?.trim() || DEFAULT_ASTRO_ASSET_CACHE_CONTROL;
const html = process.env.HTML_CACHE_CONTROL?.trim() || DEFAULT_HTML_CACHE_CONTROL;

const websiteRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = path.join(websiteRoot, "public");
const outPath = path.join(publicDir, "_headers");

const contents = [
  "# Generated by scripts/write-headers.ts — do not edit by hand.",
  "/_astro/*",
  `  Cache-Control: ${astroAssets}`,
  "",
  "/",
  `  Cache-Control: ${html}`,
  "",
  "/*",
  `  Cache-Control: ${html}`,
  "",
].join("\n");

await mkdir(publicDir, { recursive: true });

await writeFile(outPath, contents, "utf8");

console.log(`_headers → ${outPath}`);
